### ISSUE TITLE
e on SQHResult should edit current row

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/SQHell.vim#11]

**Comment by jbyte** [comment]
Hello!

I did some thinking about this and the insert current row issue. And I would like to know your opinion on how to do it.
My idea was to open a new buffer with the row values as an csv(it's probably the simplest way?).
Any better ideas?

**Comment by joereynolds** [comment]
Hey @jbyte 

That's pretty much a simpler version of what I was thinking, go for it!

**Comment by jbyte** [comment]
Implemented in #36.
