### ISSUE TITLE
SQHExecuteLine and SQHExecuteBlock without range does the same

### ISSUE THREAD

**Issue by hauleth** [joereynolds/SQHell.vim#31]
There is no need for `SQHExecuteBlock` and separate `SQHExecuteLine` as documentation states that:

```
	-range	    Range allowed, default is current line
```

I would replace them with one command `SQHExecute`.

**Comment by joereynolds** [comment]
Agreed, consider it on the list

**Comment by hauleth** [comment]
Overall public API could be reduced I think. `SHQExecute` would execute current line or selection `SQHExecute!` would execute current file or given file.

**Comment by joereynolds** [comment]
Again, I agree. The public API definitely needs some slimming down.

The less code the better!

**Comment by joereynolds** [comment]
How's this?

https://github.com/joereynolds/SQHell.vim/commit/8e63fe7147c0b408ec8c126ef2c0b0514cc66087

Nothing like learning as you go ey? ha
