### ISSUE TITLE
Can't run multiple queries in psql

### ISSUE THREAD

**Issue by misterbuckley** [joereynolds/SQHell.vim#40]
When doing SQHExecute or SQHExecuteFile with multiple select statements, psql only returns results for the first query. This is a limitation in how psql itself handles the "-c" argument on the command line and the solution is to pass in commands with an echo and a pipe, a la `echo "select * from user; select * from person;" | psql ...` . I am currently working on a solution and should have this fixed shortly

**Comment by joereynolds** [comment]
Great stuff, I don't use postgres so I'm grateful for any help I get from actual users :D

**Comment by misterbuckley** [comment]
Should be fixed in #41

**Comment by joereynolds** [comment]
https://github.com/joereynolds/SQHell.vim/commit/82827da8d85c0c1ede2ff4f0e5819f8357a634df
