### ISSUE TITLE
Allow to specify database in mysql connection

### ISSUE THREAD

**Issue by petobens** [joereynolds/SQHell.vim#50]
The MySql connection should allow to specify a database. This allow queries that were written like this: 
```sql
SELECT * FROM my_database.my_table
``` 
to be written like `SELECT * FROM my_table`.

Thanks in advance (excellent plugin BTW)

**Comment by joereynolds** [comment]
Hi!

Glad you like it :D 
I'll look at getting this done when I have the time

**Comment by joereynolds** [comment]
- [x] Allow the connection to work with and without a database
- [x] Test the generation of the `mysql` system command. i.e. is it contstructed properly with and without a database?
- [x] Make sure we don't need to prefix a database in `SQHExecute` and friends

**Comment by joereynolds** [comment]
Hey @petobens 

This is done, care to try it out?
https://github.com/joereynolds/SQHell.vim/commit/d1cd6cfd7c5aa84259d2b759cd51f12673339420

Thanks!

**Comment by petobens** [comment]
Seems to work great! Thanks
