### ISSUE TITLE
Better table chars when using utf-8

### ISSUE THREAD

**Issue by wsdjeg** [joereynolds/SQHell.vim#56]
@joereynolds I like this plugin, but the table use `-` `*` `+`, I think maybe we can use a better character.

please check out https://github.com/wsdjeg/SourceCounter.vim

**Comment by wsdjeg** [comment]
if you like this feature, I will try to send a PR. :)

**Comment by joereynolds** [comment]
Hey @wsdjeg,

The output of the tables isn't anything that SQHell does, it's what is returned from the SQL client.
For example sqlite doesn't format anything as a table at all whereas MySQL (what I think you're seeing) does.

While it's a good idea I don't think it's something I want at this time in the plugin as it would only work for  MySQL and maybe Postgres whilst introducing what I imagine to be quite a lot of code.

Nice idea though! :D

**Comment by wsdjeg** [comment]
@joereynolds oh, sorry I just think the table is created by yourself. so clossing.
