### ISSUE TITLE
dd on SQHresult should delete row

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/SQHell.vim#8]

**Comment by jbyte** [comment]
Hi!

I've been tinkering a bit on this issue and found a simple enough way to do it.
The basic idea was to save the current window number(SQHResult buffer) and then jump to the previous one(SQHTable buffer), get the table and database name and return to the result buffer.
But that relays on the user not jumping around the opened windows or closing them.
So I would like to get your input on the matter, if its fine or should I find another way to do it?

**Comment by joereynolds** [comment]
Hey jbyte,

I say go for it, the implementation can always be improved as we go on.
I'm interested in how you're going to construct the `DELETE` query though as not all table will necessarily have primary keys. 

Either way, excited to see the result!

**Comment by jbyte** [comment]
I added a explanation in the PR #25.

**Comment by joereynolds** [comment]
https://github.com/joereynolds/SQHell.vim/commit/1252fd5249d8439db83b1301fe64fc9b07d33976
